version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/todoList
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
