import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-sans`}>
        <main className="flex min-h-screen flex-col items-center gap-4 bg-gradient-to-b from-blue-800 to-indigo-900 p-24">
          <h1 className="w-full scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-white lg:text-5xl">
            Todo List
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
}
